// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import chaindata "highway/chaindata"
import mock "github.com/stretchr/testify/mock"

// PeerStore is an autogenerated mock type for the PeerStore type
type PeerStore struct {
	mock.Mock
}

// GetPeerHasBlk provides a mock function with given fields: blkHeight, committeeID
func (_m *PeerStore) GetPeerHasBlk(blkHeight uint64, committeeID byte) ([]chaindata.PeerWithBlk, error) {
	ret := _m.Called(blkHeight, committeeID)

	var r0 []chaindata.PeerWithBlk
	if rf, ok := ret.Get(0).(func(uint64, byte) []chaindata.PeerWithBlk); ok {
		r0 = rf(blkHeight, committeeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chaindata.PeerWithBlk)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, byte) error); ok {
		r1 = rf(blkHeight, committeeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
